# site settings

title: Камила Хайретдинова
description: Cпециалист по исламским финансам, шариатский эксперт.
taglong: Камила Хайретдинова – специалист по исламским финансам, шариатский эксперт.V
tagshort: Камила Хайретдинова
url: https://kamilatoday.ru
baseurl: ""
permalink: pretty
repo: https://github.com/kamilatoday/kamilatoday.github.io

# author settings

author:
  name: Камила Хайретдинова
  email: kamilatoday@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  telegram: kamilatoday
  instagram: kamilatoday

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
